FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY producer.py /app/producer.py

ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "producer.py"]



